version: '1.0'

services:
  nest: 
    container_name: nest
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app
    command:  npm run start:dev
    
  db: 
    container_name: db
    image: postgres:14.2
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgressql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_DATABASE}
    env_file:
      - .env
    
  

    